site_name: Print Tracker Documentation
theme:
  name: material
  custom_dir: overrides

nav:
  - Web Admin:
      - Overview: webadmin/overview.md
      - Concepts:
          - Entities, Users, and Installs: webadmin/concepts/entities-users-and-installs.md
          - Devices: webadmin/concepts/devices.md
          - Settings: webadmin/concepts/settings.md
          - Roles and Permissions: webadmin/concepts/roles-and-permissions.md
          - Jobs and Tasks: webadmin/concepts/jobs-and-tasks.md
#      - Getting Started: something.md
#      - Jobs and DCAs: something.md
#      - Configuring Settings: something.md
      - Settings:
          - Overview: webadmin/settings/overview.md
      - Billing Preferences:
          - Billing Schedule: webadmin/billing-preferences/billing-schedule.md
          - Billing Meters: webadmin/billing-preferences/billing-meters.md
      - Auto-fulfillment:
          - Supplies Network: webadmin/auto-fulfillment/supplies-network.md
      - Fleet Management:
          - Devices: webadmin/fleet-management/devices.md
      - Reporting and Analysis:
          - Custom Reports: webadmin/reporting-and-analysis/custom-reports.md
          - Device History: webadmin/reporting-and-analysis/device-history.md
          - Table Schema Viewer: webadmin/reporting-and-analysis/table-schema-viewer.md
      - Remote Technician:
          - Overview: webadmin/remote-technician/overview.md
          - Whitepaper: webadmin/remote-technician/whitepaper.md
  - Data Collection Agent:
      - System Requirements: dca/system-requirements.md
      - Setup & Registration: dca/setup.md
      - Whitepaper: dca/whitepaper.md
  - Data Processor:
      - Overview: dataprocessor/overview.md
  - API:
      - Endpoints: api/endpoints.md
      - Types: api/types.md
  - Best Practices:
      - Fleet Management: best-practices/fleet-management.md
#  - Whitepapers:
#      - Data Collection Agent: something.md
#      - Remote Technician: something.md


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - def_list
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css
  - stylesheets/open-sans.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
